name: release

on:
  release:
    types:
      - created

jobs:
  build_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz


  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.14"
      CIBW_ARCHS: auto64
      # CIBW_ARCHS_MACOS: "x86_64 arm64"
      CIBW_SKIP: cp36-* cp37-* cp38-macosx_arm64

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}
          path: ./wheelhouse/*.whl


  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: Download sdist
        with:
          name: sdist
          path: dist

      - uses: actions/download-artifact@v4
        name: Download wheels
        with:
          pattern: wheel-*
          path: dist
          merge-multiple: true

